# Generated by Django 3.2.8 on 2021-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
