# Generated by Django 3.2.8 on 2021-10-26 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='producttitle',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
