# Generated by Django 3.2.8 on 2021-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211026_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='producttitle',
        ),
        migrations.AddField(
            model_name='message',
            name='product_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
