# Generated by Django 3.2.8 on 2021-10-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211026_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
